-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- ColorMyPencils("flow")
-- ColorMyPencils("catppuccin-mocha")
-- ColorMyPencils("rose-pine-moon")
-- ColorMyPencils("nightfly")
ColorMyPencils("tokyonight")
ColorMyPencils("dracula")
ColorMyPencils("tokyodark")
ColorMyPencils("rose-pine-moon")
-- ColorMyPencils("solarized-osaka")
-- ColorMyPencils("catppuccin-frappe")
-- vim.cmd.colorscheme("gruvbox")
-- vim.cmd.colorscheme("rose-pine")
-- vim.cmd.colorscheme("catppuccin")
-- vim.cmd.colorscheme("tokyonight")
