-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- vim.cmd.colorscheme("rose-pine")
-- ColorMyPencils("solarized-osaka")
-- vim.cmd.colorscheme("solarized-osaka")
vim.cmd.colorscheme("gruvbox-material")
-- ColorMyPencils("solarized-osaka")
-- vim.cmd.colorscheme("solarized-osaka")
-- ColorMyPencils("catppuccin-frappe")
-- vim.cmd.colorscheme("gruvbox")
-- vim.cmd.colorscheme("rose-pine")
-- vim.cmd.colorscheme("catppuccin")
-- vim.cmd.colorscheme("tokyonight")
